{
  try {
    return cache().get(key,invoker);
  }
 catch (  final ExecutionException e) {
    if (e.getCause() instanceof AuthException) {
      throw (AuthException)e.getCause();
    }
 else {
      throw new AuthException(e);
    }
  }
}
