{
  LOG.debug(e.getCause(),e.getCause());
  super.exceptionCaught(ctx,e);
}
