{
  EventRecord.here(CallbackListenerSequence.class,EventType.CALLBACK,"fireException(" + t.getClass().getName() + ")").extreme();
  for (  Callback.Checked<? super R> cb : this.failureCallbacks) {
    try {
      EventRecord.here(this.getClass(),EventType.CALLBACK,"" + cb.getClass(),"fireException(" + t.getClass().getCanonicalName() + ")").extreme();
      cb.fireException(t);
    }
 catch (    Exception t2) {
      this.LOG.error("Exception occurred while trying to call: " + cb.getClass() + ".failure( "+ t.getMessage()+ " )");
      this.LOG.error(t2,t2);
    }
  }
}
