{
  boolean fail=false;
  try {
    runnable.run();
    fail=true;
  }
 catch (  Throwable t) {
    assertMatches(t,throwableHierarchy);
    exceptionConsumer.accept(t);
  }
  if (fail) {
    fail("No exception was thrown");
  }
}
